<a href="https://colab.research.google.com/github/ahcamachod/2279-data-science-analisis-prevision-de-series-temporales/blob/clase-2/analisis_y_prevision_de_series_temporales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Science: Análisis y previsión de Series Temporales**

##**Clase 1: Preparando y procesando los datos**

###**Importando los datos**

> Consulta la documentación de la biblioteca Pandas [aquí](https://pandas.pydata.org/).

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/ahcamachod/2279-data-science-analisis-prevision-de-series-temporales/refs/heads/main/bicicletas.csv',sep=',')

In [ ]:
df.head()

,fecha_hora,conteo,temperatura,sensacion_termica,humedad,velocidad_viento,clima,festivo,fin_de_semana,estacion
0,2023-01-04 00:00:00,182,3.0,2.0,93.0,6.0,Nublado,No,Sí,Invierno
1,2023-01-04 01:00:00,138,NaN,NaN,93.0,5.0,Cielo abierto,No,Sí,Invierno
2,2023-01-04 02:00:00,134,2.5,2.5,96.5,0.0,Cielo abierto,No,Sí,Invierno
3,2023-01-04 03:00:00,72,2.0,2.0,100.0,0.0,Cielo abierto,No,Sí,Invierno
4,2023-01-04 04:00:00,47,NaN,NaN,93.0,6.5,Cielo abierto,No,Sí,Invierno

###**Tratando los datos nulos**

In [ ]:
df.shape

(17429, 10)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17429 entries, 0 to 17428
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   fecha_hora         17429 non-null  object
 1   conteo             17429 non-null  int64
 2   temperatura        17406 non-null  float64
 3   sensacion_termica  17406 non-null  float64
 4   humedad            17429 non-null  float64
 5   velocidad_viento   17429 non-null  float64
 6   clima              17429 non-null  object
 7   festivo            17429 non-null  object
 8   fin_de_semana      17429 non-null  object
 9   estacion           17429 non-null  object
dtypes: float64(4), int64(1), object(5)
memory usage: 1.3+ MB

In [ ]:
df.isnull().sum()

fecha_hora            0
conteo                0
temperatura          23
sensacion_termica    23
humedad               0
velocidad_viento      0
clima                 0
festivo               0
fin_de_semana         0
estacion              0
dtype: int64

>Consulta la documentación detallada del método *interpolate()* de la biblioteca Pandas [aquí](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.interpolate.html).

In [ ]:
df['temperatura'] = df['temperatura'].interpolate(method='linear')
df['sensacion_termica'] = df['sensacion_termica'].interpolate(method='linear')

In [ ]:
df.head(10)

,fecha_hora,conteo,temperatura,sensacion_termica,humedad,velocidad_viento,clima,festivo,fin_de_semana,estacion
0,2023-01-04 00:00:00,182,3.00,2.00,93.0,6.0,Nublado,No,Sí,Invierno
1,2023-01-04 01:00:00,138,2.75,2.25,93.0,5.0,Cielo abierto,No,Sí,Invierno
2,2023-01-04 02:00:00,134,2.50,2.50,96.5,0.0,Cielo abierto,No,Sí,Invierno
3,2023-01-04 03:00:00,72,2.00,2.00,100.0,0.0,Cielo abierto,No,Sí,Invierno
4,2023-01-04 04:00:00,47,2.00,2.00,93.0,6.5,Cielo abierto,No,Sí,Invierno
5,2023-01-04 05:00:00,46,2.00,2.00,93.0,4.0,Cielo abierto,No,Sí,Invierno
6,2023-01-04 06:00:00,51,1.00,-1.00,100.0,7.0,Parcialmente nublado,No,Sí,Invierno
7,2023-01-04 07:00:00,75,1.00,-1.00,100.0,7.0,Parcialmente nublado,No,Sí,Invierno
8,2023-01-04 08:00:00,131,1.50,-1.00,96.5,8.0,Parcialmente nublado,No,Sí,Invierno
9,2023-01-04 09:00:00,301,2.00,-0.50,100.0,9.0,Nublado,No,Sí,Invierno

###**Identificando y eliminando datos duplicados**

In [ ]:
df.duplicated().sum()

np.int64(15)

In [ ]:
duplicados= df.duplicated(keep=False)
filas_duplicadas =df[duplicados]
filas_duplicadas.sort_values(by='fecha_hora')

,fecha_hora,conteo,temperatura,sensacion_termica,humedad,velocidad_viento,clima,festivo,fin_de_semana,estacion
519,2023-01-25 16:00:00,1238,8.0,5.0,71.0,18.0,Nublado,No,Sí,Invierno
17422,2023-01-25 16:00:00,1238,8.0,5.0,71.0,18.0,Nublado,No,Sí,Invierno
869,2023-02-09 06:00:00,479,5.0,3.5,87.0,6.5,Parcialmente nublado,No,No,Invierno
17417,2023-02-09 06:00:00,479,5.0,3.5,87.0,6.5,Parcialmente nublado,No,No,Invierno
3655,2023-06-05 18:00:00,3411,23.0,23.0,50.0,26.0,Parcialmente nublado,No,No,Verano
17425,2023-06-05 18:00:00,3411,23.0,23.0,50.0,26.0,Parcialmente nublado,No,No,Verano
4167,2023-06-27 02:00:00,337,15.5,15.5,74.5,18.0,Parcialmente nublado,No,Sí,Verano
17421,2023-06-27 02:00:00,337,15.5,15.5,74.5,18.0,Parcialmente nublado,No,Sí,Verano
4658,2023-07-17 14:00:00,1882,24.5,24.5,44.0,29.5,Parcialmente nublado,No,No,Verano
17418,2023-07-17 14:00:00,1882,24.5,24.5,44.0,29.5,Parcialmente nublado,No,No,Verano
17428,2023-08-15 23:00:00,759,17.0,17.0,59.0,6.0,Cielo abierto,No,Sí,Verano
5360,2023-08-15 23:00:00,759,17.0,17.0,59.0,6.0,Cielo abierto,No,Sí,Verano
17426,2023-12-12 11:00:00,1100,12.0,12.0,82.0,20.0,Lluvia leve,No,Sí,Invierno
8174,2023-12-12 11:00:00,1100,12.0,12.0,82.0,20.0,Lluvia leve,No,Sí,Invierno
17420,2023-12-12 12:00:00,1308,13.0,13.0,77.0,26.0,Lluvia leve,No,Sí,Invierno
8175,2023-12-12 12:00:00,1308,13.0,13.0,77.0,26.0,Lluvia leve,No,Sí,Invierno
17415,2023-12-27 05:00:00,57,15.0,15.0,72.0,31.0,Parcialmente nublado,No,Sí,Invierno
8528,2023-12-27 05:00:00,57,15.0,15.0,72.0,31.0,Parcialmente nublado,No,Sí,Invierno
17427,2024-02-02 17:00:00,2846,8.0,4.5,59.5,23.0,Parcialmente nublado,No,No,Invierno
9428,2024-02-02 17:00:00,2846,8.0,4.5,59.5,23.0,Parcialmente nublado,No,No,Invierno
17414,2024-05-06 03:00:00,77,9.5,9.0,79.0,6.0,Cielo abierto,No,No,Primavera
11646,2024-05-06 03:00:00,77,9.5,9.0,79.0,6.0,Cielo abierto,No,No,Primavera
12350,2024-06-04 11:00:00,1779,15.5,15.5,85.5,8.0,Nublado,No,Sí,Verano
17419,2024-06-04 11:00:00,1779,15.5,15.5,85.5,8.0,Nublado,No,Sí,Verano
12443,2024-06-08 08:00:00,4672,18.0,18.0,83.0,2.0,Cielo abierto,No,No,Verano
17416,2024-06-08 08:00:00,4672,18.0,18.0,83.0,2.0,Cielo abierto,No,No,Verano
17424,2024-12-11 10:00:00,1098,7.5,4.5,87.0,16.0,Cielo abierto,No,Sí,Invierno
16848,2024-12-11 10:00:00,1098,7.5,4.5,87.0,16.0,Cielo abierto,No,Sí,Invierno
17423,2024-12-23 02:00:00,92,7.5,5.5,90.0,10.0,Cielo abierto,No,No,Invierno
17128,2024-12-23 02:00:00,92,7.5,5.5,90.0,10.0,Cielo abierto,No,No,Invierno

>Consulta la documentación del método *drop_duplicates()* de la biblioteca Pandas [aquí](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html).

In [ ]:
df_limpio = df.drop_duplicates()

In [ ]:
df_limpio.shape

(17414, 10)

##**Clase 2: Explorando los datos numéricos**

###**Obteniendo las estadísticas descriptivas**

###**Analizando las distribuciones**

> La documentación de las bibliotecas de visualización puede ser consultada a través de los siguientes links:
> * [Seaborn: Statistical Data Visualization](https://seaborn.pydata.org/)
> * [Matplotlib: Visualization with Python](https://matplotlib.org/)

###**Investigando relaciones entre variables**

> **Prompt:** Genera 4 gráficos de tipo scatterplot utilizando python con las bibliotecas seaborn y matplotlib, para las variables temperatura, sensacion_termica, humedad, velocidad_viento con la columna conteo en el eje "y". Coloca los gráficos en la posición 2X2. Cada gráfico debe tener su respectivo título.

###**Examinando la correlación entre las variables**

La correlación es una medida estadística que describe la relación entre dos variables. Existen diferentes tipos de correlación, pero la correlación de Pearson es una de las más comunes. La correlación de Pearson mide la fuerza y la dirección de una relación lineal entre dos variables. Produce un valor de correlación que varía de -1 a 1.

>Consulta la documentación detallada del método *corr()* de la biblioteca Pandas [aquí](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.corr.html).

##**Clase 3: Explorando los datos categóricos**

###**Obteniendo las estadísticas descriptivas**

###**Comparando días útiles, festivos y fines de semana**

###**Investigando cómo el clima afecta la demanda**

###**Analizando las distribuciones por estación**

Formulando las hipótesis:

$H_0:$ Las distribuciones son iguales.\
$H_1:$ Las distribuciones son diferentes.

> Encuentra la documentación detallada sobre *mannwhitneyu* de la biblioteca scipy [aquí](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mannwhitneyu.html).

El *p value* menor que 0.05 sugiere que los resultados observados son improbables de ocurrir solo por azar. Por lo tanto, rechazamos la hipótesis nula en favor de la hipótesis alternativa, concluyendo que existen evidencias estadísticamente significativas para respaldar la hipótesis alternativa.

##**Clase 4: Analizando datos a lo largo del tiempo**

###**Convirtiendo tipos de datos**

###**Analizando la demanda por horario**

###**Analizando la demanda por día y mes**

##**Clase 5: Construyendo el modelo predictivo**

###**Realizando la previsión**

> Consulta la documentación de la biblioteca Prophet [aquí](https://facebook.github.io/prophet/).

###**Explorando los resultados de la previsión**

La biblioteca Prophet utiliza un modelo aditivo que incluye componentes estacionales y de tendencia. La ecuación utilizada por Prophet para realizar predicciones puede representarse de la siguiente forma:

$y(t) = g(t) + s(t) + h(t) + \epsilon_t$

Donde:

- $y(t)$ es el valor observado en la serie temporal en el tiempo \( t \).
- $g(t)$ es la componente de tendencia que modela cambios de largo plazo.
- $s(t)$ es la componente estacional que modela patrones periódicos o estacionales.
- $h(t)$ es la componente de efecto de feriados.
- $\epsilon_t$ es el error aleatorio en la predicción.

Cada una de estas componentes se modela por separado. La componente de tendencia, $g(t)$, se modela frecuentemente como una función logística o polinómica. La componente estacional, $s(t)$, se modela utilizando el análisis de Fourier para capturar patrones periódicos. La componente de feriados, $h(t)$, se modela como un efecto aditivo para cada feriado especificado.

Por lo tanto, la ecuación completa utilizada por Prophet para realizar predicciones es una suma de estos componentes más el error aleatorio.

> Aunque en nuestro proyecto no hemos detallado la inclusión de los feriados en el modelo, es importante resaltar que esta posibilidad existe.

###**Separando los datos para entrenamiento y prueba**

Separar los datos en conjuntos de entrenamiento y prueba es fundamental en modelos de series temporales para evaluar la capacidad de generalización del modelo. Imagina que estás entrenando un modelo para predecir el número de ventas de una empresa. Si entrenas el modelo con todos los datos disponibles y luego lo pruebas con los mismos datos, puede parecer excelente, pero en la práctica puede fallar al predecir el futuro.

Esto sucede porque el modelo puede simplemente memorizar los patrones específicos de los datos de entrenamiento, sin realmente aprender a identificar patrones generales que se apliquen a nuevos datos. Al separar los datos en entrenamiento y prueba, simulas el escenario de predicción futura, garantizando que el modelo sea evaluado en su capacidad de generalización, es decir, en su habilidad para hacer predicciones precisas en datos que nunca ha visto antes. Esto ayuda a garantizar que el modelo sea robusto y confiable cuando se utilice para hacer predicciones en el mundo real.

###**Obteniendo las métricas**

La métrica MSE *(Mean Squared Error)* es una medida común de evaluación del desempeño para modelos de regresión y predicción. Calcula el promedio de los cuadrados de las diferencias entre los valores previstos por el modelo y los valores reales observados en los datos de prueba. Matemáticamente, el MSE se calcula mediante la fórmula:

$MSE = \frac{\sum_{} (y_i - \hat{y}_i)^2}{n}$

Sin embargo, el MSE tiene una limitación: sus unidades son cuadráticas con respecto a las unidades originales de los datos. Esto puede dificultar la interpretación de su valor.

Para superar esta limitación, muchas veces es preferible usar el RMSE *(Root Mean Squared Error)*. El RMSE es simplemente la raíz cuadrada del MSE y se calcula mediante la fórmula:

$RMSE = \sqrt{MSE}$

##**Clase 6: Mejorando las previsiones**

###**Ajustando los datos**

###**Tratando los outliers**

###**Entrenando con los datos tratados**

###**Expandiendo el período de previsión**